const tiers = {
  UNRANKED: "UNRANKED",
  IRON: "IRON",
  BRONZE: "BRONZE",
  SILVER: "SILVER",
  GOLD: "GOLD",
  PLATINUM: "PLATINUM",
  EMERALD: "EMERALD",
  MASTER: "MASTER",
  GRANDMASTER: "GRANDMASTER",
  CHALLENGER: "CHALLENGER" ,
}; 

const summonerSpells = [
  { id: 21, name: "SummonerBarrier" },
  { id: 1, name: "SummonerBoost" },
  { id: 14, name: "SummonerDot" },
  { id: 3, name: "SummonerExhaust" },
  { id: 4, name: "SummonerFlash" },
  { id: 6, name: "SummonerHaste" },
  { id: 7, name: "SummonerHeal" },
  { id: 13, name: "SummonerMana" },
  { id: 11, name: "SummonerSmite" },
  { id: 12, name: "SummonerTeleport" },
];

const runePaths = [
  { id: 8000, code: "7201_Precision", name: "Precision" },
  { id: 8100, code: "7200_Domination", name: "Domination" },
  { id: 8200, code: "7202_Sorcery", name: "Sorcery" },
  { id: 8300, code: "7203_Whimsy", name: "Inspiration" },
  { id: 8400, code: "7204_Resolve", name: "Resolve" },
];

const runes = [
  { id: 8112, name: "Electrocute", iconURL: "Electrocute/Electrocute" },
  { id: 8128, name: "DarkHarvest", iconURL: "DarkHarvest/DarkHarvest" },
  { id: 9923, name: "HailOfBlades", iconURL: "HailOfBlades/HailOfBlades" },
  { id: 8126, name: "CheapShot", iconURL: "CheapShot/CheapShot" },
  { id: 8139, name: "TasteofBlood", iconURL: "TasteofBlood/GreenTerror_TasteOfBlood" },
  { id: 8143, name: "SuddenImpact", iconURL: "SuddenImpact/SuddenImpact" },
  { id: 8137, name: "SixthSense", iconURL: "SixthSense/SixthSense" },
  { id: 8140, name: "GrislyMementos", iconURL: "GrislyMementos/GrislyMementos" },
  { id: 8141, name: "DeepWard", iconURL: "DeepWard/DeepWard" },
  { id: 8135, name: "TreasureHunter", iconURL: "TreasureHunter/TreasureHunter" },
  { id: 8105, name: "RelentlessHunter", iconURL: "RelentlessHunter/RelentlessHunter" },
  { id: 8106, name: "UltimateHunter", iconURL: "UltimateHunter/UltimateHunter" },
  { id: 8351, name: "GlacialAugment", iconURL: "GlacialAugment/GlacialAugment" },
  { id: 8360, name: "UnsealedSpellbook", iconURL: "UnsealedSpellbook/UnsealedSpellbook" },
  { id: 8369, name: "FirstStrike", iconURL: "FirstStrike/FirstStrike" },
  { id: 8306, name: "HextechFlashtraption", iconURL: "HextechFlashtraption/HextechFlashtraption" },
  { id: 8304, name: "MagicalFootwear", iconURL: "MagicalFootwear/MagicalFootwear" },
  { id: 8321, name: "CashBack", iconURL: "CashBack/CashBack2" },
  { id: 8313, name: "TripleTonic", iconURL: "PerfectTiming/AlchemistCabinet" },
  { id: 8352, name: "TimeWarpTonic", iconURL: "TimeWarpTonic/TimeWarpTonic" },
  { id: 8345, name: "BiscuitDelivery", iconURL: "BiscuitDelivery/BiscuitDelivery" },
  { id: 8347, name: "CosmicInsight", iconURL: "CosmicInsight/CosmicInsight" },
  { id: 8410, name: "ApproachVelocity", iconURL: "ApproachVelocity/ApproachVelocity" },
  { id: 8316, name: "JackOfAllTrades", iconURL: "JackOfAllTrades/JackofAllTrades2" },
  { id: 8005, name: "PressTheAttack", iconURL: "PressTheAttack/PressTheAttack" },
  { id: 8008, name: "LethalTempo", iconURL: "LethalTempo/LethalTempoTemp" },
  { id: 8021, name: "FleetFootwork", iconURL: "FleetFootwork/FleetFootwork" },
  { id: 8010, name: "Conqueror", iconURL: "Conqueror/Conqueror" },
  { id: 9101, name: "AbsorbLife", iconURL: "AbsorbLife/AbsorbLife" },
  { id: 9111, name: "Triumph", iconURL: "Triumph/Triumph" },
  { id: 8009, name: "PresenceOfMind", iconURL: "PresenceOfMind/PresenceOfMind" },
  { id: 9104, name: "LegendAlacrity", iconURL: "LegendAlacrity/LegendAlacrity" },
  { id: 9105, name: "LegendHaste", iconURL: "LegendHaste/LegendHaste" },
  { id: 9103, name: "LegendBloodline", iconURL: "LegendBloodline/LegendBloodline" },
  { id: 8014, name: "CoupDeGrace", iconURL: "CoupDeGrace/CoupDeGrace" },
  { id: 8017, name: "CutDown", iconURL: "CutDown/CutDown" },
  { id: 8299, name: "LastStand", iconURL: "LastStand/LastStand" },
  { id: 8437, name: "GraspOfTheUndying", iconURL: "GraspOfTheUndying/GraspOfTheUndying" },
  { id: 8439, name: "Aftershock", iconURL: "Aftershock/Aftershock" },
  { id: 8465, name: "Guardian", iconURL: "VeteranAftershock/VeteranAftershock" },
  { id: 8446, name: "Demolish", iconURL: "Demolish/Demolish" },
  { id: 8463, name: "FontOfLife", iconURL: "FontOfLife/FontOfLife" },
  { id: 8401, name: "ShieldBash", iconURL: "ShieldBash/ShieldBash" },
  { id: 8429, name: "Conditioning", iconURL: "Conditioning/Conditioning" },
  { id: 8444, name: "SecondWind", iconURL: "SecondWind/SecondWind" },
  { id: 8473, name: "BonePlating", iconURL: "BonePlating/BonePlating" },
  { id: 8451, name: "Overgrowth", iconURL: "Overgrowth/Overgrowth" },
  { id: 8453, name: "Revitalize", iconURL: "Revitalize/Revitalize" },
  { id: 8242, name: "Unflinching", iconURL: "Unflinching/Unflinching" },
  { id: 8214, name: "SummonAery", iconURL: "SummonAery/SummonAery" },
  { id: 8229, name: "ArcaneComet", iconURL: "ArcaneComet/ArcaneComet" },
  { id: 8230, name: "PhaseRush", iconURL: "PhaseRush/PhaseRush" },
  { id: 8224, name: "AxiomArcanist", iconURL: "NullifyingOrb/Axiom_Arcanist" },
  { id: 8226, name: "ManaflowBand", iconURL: "ManaflowBand/ManaflowBand" },
  { id: 8275, name: "NimbusCloak", iconURL: "NimbusCloak/6361" },
  { id: 8210, name: "Transcendence", iconURL: "Transcendence/Transcendence" },
  { id: 8234, name: "Celerity", iconURL: "Celerity/CelerityTemp" },
  { id: 8233, name: "AbsoluteFocus", iconURL: "AbsoluteFocus/AbsoluteFocus" },
  { id: 8237, name: "Scorch", iconURL: "Scorch/Scorch" },
  { id: 8232, name: "Waterwalking", iconURL: "Waterwalking/Waterwalking" },
  { id: 8236, name: "GatheringStorm", iconURL: "GatheringStorm/GatheringStorm" }
];

const queueData = [
  { queueId: 0, map: "Custom games", description: "Custom Game" },
  { queueId: 2, map: "Summoner's Rift", description: "5v5 Blind Pick" },
  { queueId: 4, map: "Summoner's Rift", description: "5v5 Ranked Solo" },
  { queueId: 6, map: "Summoner's Rift", description: "5v5 Ranked Premade" },
  { queueId: 7, map: "Summoner's Rift", description: "Co-op vs AI" },
  { queueId: 8, map: "Twisted Treeline", description: "3v3 Normal" },
  { queueId: 9, map: "Twisted Treeline", description: "3v3 Ranked Flex" },
  { queueId: 14, map: "Summoner's Rift", description: "5v5 Draft Pick" },
  { queueId: 16, map: "Crystal Scar", description: "5v5 Dominion Blind Pick" },
  { queueId: 25, map: "Crystal Scar", description: "Dominion Co-op vs AI" },
  { queueId: 31, map: "Summoner's Rift", description: "Co-op vs AI Intro Bot" },
  { queueId: 32, map: "Summoner's Rift", description: "Co-op vs AI Beginner Bot" },
  { queueId: 33, map: "Summoner's Rift", description: "Co-op vs AI Intermediate Bot" },
  { queueId: 400, map: "Summoner's Rift", description: "5v5 Draft Pick" },
  { queueId: 420, map: "Summoner's Rift", description: "5v5 Ranked Solo" },
  { queueId: 430, map: "Summoner's Rift", description: "5v5 Blind Pick" },
  { queueId: 440, map: "Summoner's Rift", description: "5v5 Ranked Flex" },
  { queueId: 450, map: "Howling Abyss", description: "5v5 ARAM" },
  { queueId: 700, map: "Summoner's Rift", description: "Clash" },
  { queueId: 900, map: "Summoner's Rift", description: "ARURF" },
  { queueId: 1020, map: "Summoner's Rift", description: "One for All" },
];

export { tiers, summonerSpells, runePaths, runes, queueData };